/* ───────── DATA ─────────
   Every country ranked in at least one source comes from ALL_COUNTRIES
   (js/countries.js, generated by scripts/build_data.py). Per country:
     score / whr  WHR life evaluation, 3-year average 2025 (score and rank)
     prev         WHR rank in 2024
     wb/pos/neg   Wellbeing Rankings, countries only (of 164): overall / positive / negative affect
     hpi          Happy Planet Index rank, 2025
   null = not ranked in that source. COUNTRIES is ordered by WHR rank, so
   COUNTRIES.slice(0,10) is the WHR top 10. */
// flag SVGs exist only for these (see js/flags.js)
const FLAG_CODES = {Finland:"fi", Iceland:"is", Denmark:"dk", "Costa Rica":"cr", Sweden:"se", Norway:"no",
  Netherlands:"nl", Israel:"il", Luxembourg:"lu", Switzerland:"ch", "New Zealand":"nz", Mexico:"mx",
  Ireland:"ie", Belgium:"be", Australia:"au", Kosovo:"xk", Germany:"de", Slovenia:"si", Austria:"at",
  Czechia:"cz", Taiwan:"tw"};
const COUNTRIES = ALL_COUNTRIES.map(d=>({...d, rank:d.whr, code:FLAG_CODES[d.c]||null}));

// ribbon-chart columns, left to right
const SOURCES = [
  {key:"whr", label:"World Happiness Report (Gallup Analytics)", total:147},
  {key:"wb",  label:"Wellbeing (overall)",                       total:164},
  {key:"pos", label:"Wellbeing (positive affect)",               total:164},
  {key:"neg", label:"Wellbeing (negative affect)",               total:164},
  {key:"hpi", label:"Happy Planet Index",                        total:134},
];
const COLS = SOURCES.map(s=>s.label);
// per column: indices into COUNTRIES, best rank first, unranked countries left out
const ORDERS = SOURCES.map(s=>COUNTRIES.map((_,i)=>i)
  .filter(i=>COUNTRIES[i][s.key]!=null)
  .sort((a,b)=>COUNTRIES[a][s.key]-COUNTRIES[b][s.key]));
const TOTAL = 147;

/* lowest-ranking 10 of 147 · World Happiness Report 2026, life evaluation
   average (3-year, 2023–2025) · source: 2world_happiness_all_measures.xlsx,
   "Data" + "Rankings" tabs */
const LOWEST10 = [
  {c:"Tanzania",      code:"tz", score:3.902, rank:138},
  {c:"Egypt",         code:"eg", score:3.862, rank:139},
  {c:"DR Congo",      code:"cd", score:3.761, rank:140},
  {c:"Lebanon",       code:"lb", score:3.723, rank:141},
  {c:"Yemen",         code:"ye", score:3.532, rank:142},
  {c:"Botswana",      code:"bw", score:3.464, rank:143},
  {c:"Zimbabwe",      code:"zw", score:3.346, rank:144},
  {c:"Malawi",        code:"mw", score:3.284, rank:145},
  {c:"Sierra Leone",  code:"sl", score:3.251, rank:146},
  {c:"Afghanistan",   code:"af", score:1.446, rank:147},
];
