// Build js/shapes.js: per-country outline (SVG path), population and world region
// for every country in js/countries.js.
//
//     npm install && node scripts/build_shapes.mjs
//
// Sources (downloaded at build time):
//   outlines, region   Natural Earth 1:50m admin-0 countries (public domain) — SUBREGION is the UN geoscheme
//   population         World Bank SP.POP.TOTL, 2024; Natural Earth POP_EST where the World Bank has no figure
import { readFileSync, writeFileSync } from "node:fs";
import { geoAzimuthalEqualArea, geoPath, geoArea, geoCentroid, geoDistance } from "d3-geo";

const NE_URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson";
const WB_URL = "https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?date=2024&format=json&per_page=400";
const BOX = [140, 100];          // outline is fitted inside this box (px)
const MAX_KM = 2000;             // drop parts further than this from the main landmass (Alaska, French Guiana…)
// our ISO3 / placeholder key -> Natural Earth ADM0_A3 where they differ
const NE_ALIAS = { XKX: "KOS", SSD: "SDS", "X-Somaliland": "SOL", "X-Northern Cyprus": "CYN", "X-Puerto Rico": "PRI" };

const root = new URL("..", import.meta.url);
const countries = new Function(readFileSync(new URL("js/countries.js", root), "utf8") + ";return ALL_COUNTRIES")();
const ne = await (await fetch(NE_URL)).json();
const wb = (await (await fetch(WB_URL)).json())[1];
const wbPop = Object.fromEntries(wb.filter(r => r.value != null).map(r => [r.countryiso3code, r.value]));

const byCode = {};
for (const f of ne.features) for (const k of ["ADM0_A3", "ISO_A3", "ISO_A3_EH"]) {
  const v = f.properties[k]; if (v && v !== "-99" && !byCode[v]) byCode[v] = f;
}

// path string snapped to a 0.5px grid, skipping points within ~1px of the last one kept — plenty for a
// ~140px outline, and a fraction of the size of full-precision coordinates
function compactPath(proj, shape) {
  let out = "", lx = 0, ly = 0, start = 0;
  const q = v => Math.round(v * 2) / 2;
  const ctx = {
    moveTo(x, y) { lx = q(x); ly = q(y); out += `M${lx},${ly}`; start = out.length; },
    lineTo(x, y) { x = q(x); y = q(y); if (Math.hypot(x - lx, y - ly) >= 1) { out += `L${x},${y}`; lx = x; ly = y; } },
    closePath() { out += out.length > start ? "Z" : ""; },
  };
  geoPath(proj, ctx)(shape);
  return out.replace(/M[^MZ]*(?=M|$)/g, m => (m.includes("L") ? m : "")); // drop rings that collapsed to a point
}

// keep the main polygon plus parts near it, so outlying territories don't shrink the shape
function mainland(f) {
  if (f.geometry.type !== "MultiPolygon") return f;
  const parts = f.geometry.coordinates.map(c => { const p = { type: "Polygon", coordinates: c }; return { c, area: geoArea(p), mid: geoCentroid(p) }; });
  const big = parts.reduce((a, b) => (b.area > a.area ? b : a));
  const keep = parts.filter(p => p.area >= big.area * 0.0005 && geoDistance(p.mid, big.mid) * 6371 <= MAX_KM);
  return { ...f, geometry: { type: "MultiPolygon", coordinates: keep.map(p => p.c) } };
}

const out = {}, missing = [];
for (const d of countries) {
  const f = byCode[NE_ALIAS[d.iso] || d.iso];
  if (!f) { missing.push(d.c); continue; }
  const shape = mainland(f), [lon, lat] = geoCentroid(shape);
  const proj = geoAzimuthalEqualArea().rotate([-lon, -lat]).fitExtent([[2, 2], [BOX[0] - 2, BOX[1] - 2]], shape);
  const p = f.properties, pop = wbPop[d.iso] ?? (p.POP_EST > 0 ? p.POP_EST : null);
  out[d.iso] = { d: compactPath(proj, shape), pop, popSrc: wbPop[d.iso] != null ? "World Bank 2024" : `Natural Earth ${p.POP_YEAR}`, region: p.SUBREGION || null };
}

const body = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(",\n");
writeFileSync(new URL("js/shapes.js", root),
  `/* GENERATED by scripts/build_shapes.mjs — do not edit by hand.\n   Outline (SVG path in a ${BOX[0]}x${BOX[1]} box), population and UN sub-region per country, keyed like ALL_COUNTRIES.iso. */\n` +
  `const COUNTRY_GEO = {\n${body}\n};\n`);
console.log(`${Object.keys(out).length} countries -> js/shapes.js; no outline: ${missing.join(", ") || "none"}`);
console.log("population fallback (not World Bank):", Object.entries(out).filter(([, v]) => !v.popSrc.startsWith("World")).map(([k]) => k).join(", "));
