"""Build js/countries.js from the three source workbooks in the repo root.

    python3 scripts/build_data.py

Countries are matched across sources by ISO3 code. The wellbeing workbook has
names only, so its names are mapped to ISO3 via the WHR and HPI name lists plus
the WB_ALIASES table below. A country is included if it is ranked in at least
one source.
"""
import json
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
WHR_FILE = ROOT / "2world_happiness_all_measures.xlsx"
WB_FILE = ROOT / "1wellbeing_rankings_countries.xlsx"
HPI_FILE = ROOT / "3Happy-Planet-Index-2006-2025-public-data-set.xlsx"
OUT = ROOT / "js" / "countries.js"

# wellbeing name -> ISO3, where it differs from both WHR and HPI spellings
WB_ALIASES = {
    "Bosnia Herzegovina": "BIH",
    "Congo Brazzaville": "COG",
    "Congo Kinshasa": "COD",
    "Hong Kong": "HKG",
    "Ivory Coast": "CIV",
    "Palestine": "PSE",
    "Russia": "RUS",
    "Taiwan": "TWN",
}

# shorter display names for long official WHR spellings
DISPLAY = {
    "Taiwan Province of China": "Taiwan",
    "Hong Kong SAR of China": "Hong Kong",
    "Republic of Korea": "South Korea",
    "Republic of Moldova": "Moldova",
    "Russian Federation": "Russia",
    "State of Palestine": "Palestine",
    "Lao PDR": "Laos",
    "Viet Nam": "Vietnam",
}


def load(path):
    return openpyxl.load_workbook(path, read_only=True, data_only=True)


def col_for(ws, group, year):
    rows = list(ws.iter_rows(min_row=1, max_row=3, values_only=True))
    for i, (g, y) in enumerate(zip(rows[1], rows[2])):
        if g == group and str(y) == year:
            return i
    raise KeyError(f"{group} / {year} not found in {ws.title}")


def main():
    names = {}   # iso -> {source: name}
    ranks = {}   # iso -> {whr, wb, pos, neg, hpi, score, prev}
    name_to_iso = {}

    def rec(iso):
        return ranks.setdefault(iso, {})

    # World Happiness Report: rank + score on the 3-year average, 2025; rank 2024 as prev
    wb_whr = load(WHR_FILE)
    rk, dt = wb_whr["Rankings"], wb_whr["Data"]
    c_rank, c_prev = col_for(rk, "Life evaluation: rank on 3-year average", "2025"), col_for(rk, "Life evaluation: rank on 3-year average", "2024")
    c_score = col_for(dt, "Life evaluation: average (3-year)", "2025")
    scores = {r[1]: r[c_score] for r in dt.iter_rows(min_row=4, values_only=True) if r and r[1]}
    for r in rk.iter_rows(min_row=4, values_only=True):
        if not (r and r[0] and r[1]):
            continue
        name, iso = r[0], r[1]
        name_to_iso[name] = iso
        if r[c_rank] is not None:
            names.setdefault(iso, {})["whr"] = name
            rec(iso).update(whr=int(r[c_rank]), score=scores.get(iso),
                            prev=int(r[c_prev]) if r[c_prev] is not None else None)

    # Happy Planet Index, sheet "1. All countries" (set to 2025 in the workbook)
    for r in load(HPI_FILE)["1. All countries"].iter_rows(min_row=10, values_only=True):
        if not (r and r[1] and r[2]):
            continue
        name, iso = r[1], r[2]
        name_to_iso.setdefault(name, iso)
        if isinstance(r[0], (int, float)):
            names.setdefault(iso, {})["hpi"] = name
            rec(iso)["hpi"] = int(r[0])

    # Wellbeing Rankings, countries only (of 164), derived columns
    unmatched = []
    for r in load(WB_FILE)["Overall ranks"].iter_rows(min_row=3, values_only=True):
        if not (r and r[0]):
            continue
        name = r[0]
        iso = WB_ALIASES.get(name) or name_to_iso.get(name)
        if iso is None:  # territories that only this source ranks
            iso = "X-" + name
            unmatched.append(name)
        names.setdefault(iso, {})["wb"] = name
        rec(iso).update(pos=r[4], neg=r[5], wb=r[6])

    rows = []
    for iso, rk_ in ranks.items():
        n = names[iso]
        raw = n.get("whr") or n.get("hpi") or n.get("wb")
        rows.append({
            "c": DISPLAY.get(raw, raw), "iso": iso,
            "score": round(rk_["score"], 3) if rk_.get("score") is not None else None,
            "prev": rk_.get("prev"),
            **{k: rk_.get(k) for k in ("whr", "wb", "pos", "neg", "hpi")},
        })
    big = 10**6
    rows.sort(key=lambda d: (d["whr"] or big, d["wb"] or big, d["hpi"] or big, d["c"]))

    lines = ",\n".join("  " + json.dumps(d, ensure_ascii=False) for d in rows)
    OUT.write_text(
        "/* GENERATED by scripts/build_data.py from the three source workbooks.\n"
        "   Do not edit by hand; re-run the script instead. null = not ranked in that source. */\n"
        f"const ALL_COUNTRIES = [\n{lines}\n];\n", encoding="utf-8")

    count = lambda k: sum(1 for d in rows if d[k] is not None)
    print(f"{len(rows)} countries -> {OUT.relative_to(ROOT)}")
    print("ranked per source:", {k: count(k) for k in ("whr", "wb", "pos", "neg", "hpi")})
    print("wellbeing-only territories:", unmatched)


if __name__ == "__main__":
    main()
